### PR TITLE
Related collections v2

### PR DESCRIPTION
**Pull request by krallin**
@DicsyDel, @recipe,

Please see the changes to `swagger.yaml` (note that I have also included the resulting auto-generated `swagger-complete.yaml` file so you can copy and paste that one into the swagger editor).

The main change here is that we no longer add Images directly to a Role, but instead have an intermediary `RoleImage` object (which probably better reflects the underlying M2M relation), as was discussed in the spec and seemed to be a point of contention. 

While this makes more sense in practice (Images have their own dedicated endpoint, so they shouldn't have an endpoint below Roles as well), one concern is that without nesting the information returned by `/roles/{roleId}/images/` isn't very useful (i.e. you still have to make one call per Image to figure out what's in it). 

One other thing to keep in mind here is that while the spec recommends not passing the `role` when adding a `RoleImage` to a `Role`, we can't really make that apparent in the mockup.

--

Also, do you want me to continue using the `...ForeignKey` objects, which are basically denatured version of the original objects (only the `"id"` field is kept). 

Those were added to avoid confusion about needing to pass a full or return object when only the ID was needed, but on the other hand if we attempt to auto-generate a client, they will become a problem.

### CODE REVIEW

**Comment by krallin** [comment]
Note that we could probably just remove the `role` field in the `RoleImage` object altogether since it'll always be used in the "context" of a Role.

**Comment by recipe** [comment]
All statements sounds reasonable to me. When we add Image to a Role  POST-ing to `/roles/{roleId}/images/` endpoint, the only thing we need is the two identifiers and it would be clear.

**Comment by krallin** [comment]
@recipe ,

If we POST to `/roles/{roleId}/images/`, would it make sense to let the user skip the `role` field? They've already provided it in the URL.

If we don't want to do this just now, this is something we can add afterwards. Let's just keep in mind that this will show in a variety of other places (e.g. Farm Roles, Script Versions, etc.), so we'll have to be consistent.

Cheers,

**Comment by recipe** [comment]
One identifier (roleId) is passed via request URI and this one has a priority over those passed in the body. Latter can be ignored by the server. And eventually we end up with the one identifier imageId. I feel that it could be passed in the URI (POST `/roles/{roleId}/images/{imageId}`) as well

**Comment by krallin** [comment]
We could have a PUT at that URL as another option, but I think we need to keep the POST either way, as in some cases (e.g. Farm Roles) the ID isn't controlled by the end-users (e.g. Farm Roles, where the ID is auto-generated by Scalr).

In order to not add too many options I'd rather just keep this as is. Does this make sense?

**Pull request merged**
